[OPENAI]
API_KEY="foo_bar"
MODEL="gpt-4-turbo"
EMBEDDING_MODEL_V2="text-embedding-ada-002"
EMBEDDING_MODEL_V3="text-embedding-3-small"

[ZHIPUAI]
API_KEY="foo_bar"
MODEL="glm-4"

[PINECONE]
API_KEY="foo_bar"
INDEX_NAME="tiangong"
NAMESPACE_SCI="sci"
NAMESPACE_PATENT="patent"
NAMESPACE_ESG="esg"
NAMESPACE_STANDARD="standard"

[WEAVIATE]
HOST="host.docker.internal"
PORT="8088"
COLLECTION_NAME="Tiangong"

[XATA]
API_KEY="foo_bar"
MEMORY_TABLE_NAME="agent_memory"
MEMORY_DB_URL="foo_bar"
ESG_DB_URL="foo_bar"
DOCS_DB_URL="foo_bar"

[E2B]
API_KEY="foo_bar"

[WIX]
WIX_CLIENT_ID="foo_bar"
CLIENT_ID="foo_bar"
CLIENT_SECRET="foo_bar"
OPENAI_CODE="foo_bar"

[FASTAPI]
AUTH=false
BEARER_TOKEN="foo_bar"
MIDDLEWARE_SECRECT_KEY="foo_bar"

[LANGSMITH]
TRACING_V2="true"
API_KEY="foo_bar"
